### ISSUE TITLE
Regression in rendering textured meshes imported from Wavefront OBJ files

### ISSUE THREAD

**Issue by trevorld** [tylermorganwall/rayrender#51] opened 2024-07-30 00:32 UTC
I'm observing a regression in rendering textured meshes imported from Wavefront OBJ files in recent versions of `{rayrender}` including the recent CRAN release and the development version.  Here is a minimal, reproducible example:

```r
# create Wavefront OBJ file with texture
library("piecepackr")
envir <- game_systems("sans3d")
cfg <- game_systems("sans3d")$piecepack
f <- save_piece_obj(piece_side = "tile_back", x = 0, y = 0, suit = 3, rank = 3, cfg = cfg)

# import/render Wavefront OBJ file in {rayrender}
library("rayrender")
tile <- obj_model(filename = f$obj, load_material = TRUE, load_textures = TRUE)
render_scene(tile)
```

```
Error: Loading of '/tmp/rtmpwxldz4/filece36e26388664.png' failed due to error: can't fopen-- nx/ny/channels :0/0/0
```

**Comment by trevorld** [comment] 2024-07-30 02:08
`git bisect` suggests that https://github.com/tylermorganwall/rayrender/commit/55fa9b8d7951f5827af77064cb7a6021905dce05 was the first commit our example stopped working (although I can't get that commit to compile on my laptop---more recent commits though do compile on my laptop and provide the above `Error: Loading of '/tmp/rtmpwxldz4/filece36e26388664.png' failed due to error: can't fopen-- nx/ny/channels :0/0/0`).

**Comment by tylermorganwall** [comment] 2024-08-01 01:43
I've confirmed this is fixed in 44ecc436dba538f00b2730b121b1828b3922f30e, which has been submitted to CRAN.

**Closed as completed by tylermorganwall** 2024-08-01 01:43 UTC

**Comment by trevorld** [comment] 2024-08-01 06:57
Thanks!  Awesome that you were able to submit a fix to CRAN before they went on vacation.

**Comment by tylermorganwall** [comment] 2024-08-01 14:17
The submission successfully went through, so you should be able to respond to BDR that the issue is upstream and has been addressed.
