### ISSUE TITLE
Code runs under macOS; segfault under Ubuntu and Windows

### ISSUE THREAD

**Issue by tteo** [tylermorganwall/rayrender#41] opened 2023-02-15 02:48 UTC
Hi Tyler, posting the issue as requested. Am working with a PLY object and getting a segfault under Ubuntu and Windows but not macOS. Attempted to troubleshoot and think I may have narrowed the segfault (memory not mapped) down to ply_model. OBJ works fine, as do all native rayrender objects.

**Comment by tylermorganwall** [comment] 2023-02-15 03:28
Can you provide the ply model that makes it crash?

**Comment by tteo** [comment] 2023-02-15 03:57
Sure, here's a link to the model: https://tteo.github.io/rayrender/heart.ply

_Edit to add code:_ `add_object(ply_model("heart.ply", scale = 0.25, x = 0, y = -0.5, z = 1, 
            angle = c(-90, 0, 0))) |> render_scene()`

**Comment by tylermorganwall** [comment] 2023-09-13 01:00
I just got around to hunting for the cause of this (I've confirmed it still happens on Ubuntu). It appears to be an issue with the underlying miniply library, so it might take a little longer to figure out.

**Comment by tylermorganwall** [comment] 2023-09-14 12:39
@tteo, I believe this is fixed: can you install the latest version of the plyfix branch and confirm? Thanks!

```r
remotes::install_github(“tylermorganwall/rayrender@plyfix”)
```

**Comment by tylermorganwall** [comment] 2023-09-15 01:27
I have merged the fix after re-running some local tests and confirming the crash doesn't occur--if you find out that it still does on your machine, post here and I'll reopen the issue.

**Closed as completed by tylermorganwall** 2023-09-15 01:27 UTC
